swagger: '2.0'
info:
  description: BASE URL :http://localhost:3000/user/{userId}/account/{accountId}/transaction/{transactionId}
  version: 1.0.0
  title: PingrisAlexis_13_31032022_API_DOC


  license:
    name: Apache 2.0

tags:
  - name: Transactions
    description: Operations to manage transactions details

paths:
  /transaction/{transactionId}:
    get:
      tags:
        - "Transactions"
      description: Get details from a transaction if user is connected
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: search results matching criteria
        400:
          description: bad input parameter
    post:
      tags:
        - Transactions
      description: Post details of a transaction
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: "string"
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDescription'
      responses:
        201:
          description: item created
        400:
          description: invalid input, object invalid
        500:
          description: Internal Server Error
    put:
      tags:
        - Transactions
      description: update transaction detail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: "string"
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDescription'
      responses:
        201:
          description: Transaction's Description Updated
        400:
          description: Invalid Transaction Supplied
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
    delete:
      tags:
        - Transactions
      description: delete transaction detail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction to delete
          type: integer
          required: true
        - in: header
          name: Authorization
          description: Attach Bearer JWT token.
          type: "string"
          required: true
      responses:
        200:
          description: Transaction deleted
        400:
          description: Invalid Transaction Supplied
        404:
          description: Transaction Not Found
        500:
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: Response status message
      body:
        type: object
        properties:
          id:
            type: integer
            description: transaction ID
          created:
            type: string
            description: transaction date
          description:
            type: string
            description: transaction description
          amount:
            type: number
            description: transaction amount
          balance:
            type: number
            description: account balance after transaction
          transactionType:
            type: string
            description: transaction type
          category:
            type: string
            description: transaction category
          note:
            type: string
            description: user's notes for transaction
  TransactionDescription:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
        example: Response status message
      body:
        type: object
        properties:
          id:
            type: integer
            description: transaction ID
          category:
            type: string
            description: transaction's category
          note:
            type: string
            description: user's notes for transaction
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /PingrisAlexis/PingrisAlexis_13_31032022_swagger/1.0.0
schemes:
  - https