export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const LOADING = 'LOADING'
export const REMEMBER = 'REMEMBER'
